
jobs = [
	{
	'title': 'Mixed Practice Veterinarian',
	'url': 'mixedpracticevet',
	'pub_date': 'May 24, 2019', 
	'location': 'Bundaberg, Queensland, 4670', 
	'type': 'Full time', 
	'sponsored': True, 
	'salary': 65000, 
	'description': 'Vet Cross Bundaberg is looking for another full-time veterinarian to join us in our purpose-built accredited hospital and branch clinics in Gin Gin & Bargara. Both experienced and new graduate veterinarians are invited to apply. Our high caseload of truly mixed-practice cases ensures you will get plenty of experience in all species, with the opportunity to develop almost any area of interest. Our distance from referral centres, as well as high-quality diagnostics and surgical equipment means that you will be able to make the most of your talents and develop your skills.\n\nAre you looking for a supportive team to join?\n\nAt Vet Cross, we are very proud of our well-rounded and passionate team.\n\nWe have two extremely supportive Principal Veterinarians with a genuine desire to encourage, assist and challenge you. Both are first class vets with a wealth of knowledge and a talent for teaching. Their goal is to give you the best possible start to your career, filling you with the confidence and experience to tackle anything the veterinary world can throw at you.\n\nYou would be joining seven fellow Associate Veterinarians ranging from several recent graduates to 20+ years of experience. All the vets know exactly what it is like starting out as a new grad and will ensure you never feel alone or out of your depth. Every one of them has their areas of special interest and are more than happy to share their tricks of the trade, cautionary tales or second opinion.\n\nOur nurses and administration team are the cogs that keep our very busy clinics running efficiently. They are positive, caring and highly experienced. We are lucky enough to have five qualified nurses, with the rest of the nurses studying towards their Certificate IV in Veterinary Nursing. As well as enjoying their assistance in the clinic, we have the luxury of taking a nurse out on most large animal calls.\n\nWorried about the transition from student to veterinarian?\n\nWe think it is very important to start our new graduates off on the right foot. Accordingly, we have a structured new graduate program that ensures a gradual introduction to all your veterinary responsibilities including after-hours. We also happen to be “New Graduate Friendly” accredited.\n\n\nPlease send your CV to:\n\nDr Tim Hill & Dr Andrew Marland\n\nmanagement@vetcross.com.au'},
	{
	'title': 'Veterinary Surgeon',
	'url': 'vetsurgeon', 
	'pub_date': 'June 4, 2019', 
	'location': 'AUGUSTINE HEIGHTS, Queensland, 4300', 
	'type': 'Full time', 
	'sponsored': False, 
	'salary': 90000, 
	'description': 'Well rounded general practitioner required for exciting role across two well-equipped practices located in Springfield and Augustine Heights (30 minutes west of Brisbane).\n\nWe are a 9 Vet, 100% small animal, ASAV accredited hospital delivering an interesting mix between GP and emergency cases (but no dreaded on call) ranging from vaccinations, reproductive health and general surgery to more complex medical and surgical work-ups including orthopaedics. If you are looking at advancing your knowledge in any of these areas, then this might be the position for you. We also see a high emergency case load providing opportunity for someone looking to test the waters in emergency work or simply gain some additional experience in this area.\n\nWe have all the toys - DR digital xray, modern ultrasound, new dental xray, in-house IDEXX pathology (Procyte, catalyst and Quickvet coagulation and blood typing), endoscopy, monitoring equipment including capnography, doppler, and Petmap.\n\nOur team of dedicated, experienced & efficient nursing staff are available for support so that you can remain focused to maintain a high level of patient care.\n\nDue to our extended opening hours we are able to be flexible with rostering allowing you to enjoy a good work-life balance.\n\nWe are looking for a confident and cool headed professional who can work independently under pressure but also thrives in a team environment. An excellent communicator, who can build good client rapport whilst remaining efficient and conscious of time management. We want you to be as passionate about your work and personal development as we are so that you take advantage of our paid study leave and financial incentives.\n\nThe successful applicant will receive a generous package including all the usual perks – CPD allowance, 4 weeks annual leave, 1 weeks paid study leave but most importantly the ability and flexibility to build a contract that works for you - want to work full-time? Sure, can do. Have school aged kids? No problem, part-time it is AND what\'s more, we want to pay you what you deserve.\n\nIf this sounds like you, we definitely have to meet. Please email cover letter and resume to our Practice Manager, Kelly, at manager@gsvets.com.au \n\nNot sure if this is for you? Our clinical director is more than happy to arrange coffee and a tour to discuss the position further, simply mention this in your above email to get in contact.\n\nSee our website http://springfielddistrictvets.com.au/'},
	{
	'title': 'Dispensary Coordinator',
	'url': 'coordinator', 
	'pub_date': 'June 24, 2019', 
	'location': 'Gatton, Queensland, 4343', 
	'type': 'Part time', 'sponsored': False, 
	'salary': 50000, 
	'description': 'Applicants must possess qualifications in either Veterinary Science or Pharmacy, and legally have the right to procure drugs under Queensland government legislation. You should also have a strong interest in veterinary pharmacology or practice management.\n\nYou must have ongoing unrestricted work rights in Australia to apply for this opportunity.\n\nWe value diversity and inclusion, and actively encourage applications from those who bring diversity to the University. Our Diversity and Inclusion webpage (https://staff.uq.edu.au/information-and-services/human-resources/diversity) contains further information if you require additional support. Accessibility requirements and/or adjustments can be directed to recruitment@uq.edu.au.\n\nWhat We Can Offer\n\nThis is a full-time, continuing position at HEW level 6.\n\nThe full-time equivalent base salary will be in the range $77,400 - $83,267, plus super of up to 17% and recreation leave loading of 17.5%.\n\nYou will be able to take advantage of UQ Sport Facilities (https://uqsport.com.au), salary sacrificing options, on-campus childcare, discounted private health insurance, free parking, discounted veterinary access, development programs (http://www.uq.edu.au/staffdevelopment/) and many other benefits.\n\nFor further information, please review The University of Queensland\'s Enterprise Bargaining Agreement 2018-2021 (https://staff.uq.edu.au/files/20908/enterprise-agreement-2018-2021.pdf).\n\nQuestions?\n\nTo discuss this role please contact Dain Heffernan, telephone +61-7-5460-1984 or email d.heffernan@uq.edu.au.\n\nWant to Apply?\n\nTo submit an application for this role, go to http://search.jobs.uq.edu.au/caw/en/job/507699/dispensary-coordinator and use the Apply button. All applicants must supply the following documents: Cover letter addressing key selection criteria; Resume.\n\nApplications close: 4 July 2019\n\nJob no: 507699'},
	{
	'title': 'Locum Veterinarian',
	'url': 'locumvet', 
	'pub_date': 'June 14, 2019', 
	'location': 'Gatton, Queensland, 4343', 
	'type': 'Part time', 
	'sponsored': True, 
	'salary': 60000, 
	'description': 'Full-time hours from 2nd September to the 22nd of September.\n\nWhere: Ourimbah Vet Hospital.\n10 Pacific Highway, Ourimbah 2258 NSW\nPay Rate: $50 to $65 p/hr DOE\nOther Info: Flights and Accommodation can be provided for interstate locums.\n\nREQUIREMENTS:\n\nTo be considered for the position you must be able to demonstrate:\nA minimum of 2 -3 years PQE as a GP Veterinarian.\nAbility to handle a mixed caseload of Medical and Surgical would be highly regarded.\nprevious experience in mixed practice.\nFor further information apply online or contact our VetPartners Careers Team on 042056949 or sergio.carrillo@vetpartners.com.au'},
	{
	'title': 'Experienced Veterinarian',
	'url': 'expveterinarian', 
	'pub_date': 'May 2, 2019', 
	'location': 'Epping NSW', 
	'type': 'Full time', 
	'sponsored': True, 
	'salary': 75000, 
	'description': 'We currently have a fantastic opportunity for an experienced Vet to join our Epping team, on a full-time, part-time or casual basis, taking on more responsibility and expanding their skills at a Band 3 level. The successful candidate will be required to work on a seven day rotating roster, which may include weekends and public holidays.\n\nThis role will attract a Total Fixed Remuneration (TFR) of between $91,864 - $101,111 pro rata, depending on the candidate’s level of skills, experience and knowledge associated with the role.\n\n\nThis role is a true opportunity to take that next step and expand your skills as a Vet, as well as one of the leading Vets in the team. The role is diverse and interesting, and will provide the successful candidate with an opportunity to:\n\nDeliver excellence in medical and surgical service to shelter clients.\nWork on occasions with special interest practitioners in ophthalmology, ultrasonography, internal medicine and orthopaedic surgery.\nHelp in emergency response situations.\nFurther develop mentoring skills and take on leadership roles within the team and organisation.\nBenefit from assistance with study leave and financial support for CPD requirements and studies.\nTo be successful in this role, you will need to have the following skills, experience, qualifications and licenses:\n\nVictoria Veterinary surgeon registration\nA Victorian drivers\' licence, radiation use license and microchipping implantation certificate\nA current Tetanus vaccination\nThe capability to conduct complex (band 3) clinical consultations and surgical procedures independently\nThe ability and desire to coach/mentor less experienced Vets (essential)\nStrong communication skills: both verbal and written, and exceptional organisational skills\nThe ability to operate as a team player, generate enthusiasm in the team and build effective relationships with both internal and external stakeholders\nResilience and a strong collaborative drive\nA desire to work with the community to improve animal welfare outcomes\nAble to work across a seven day rotating roster including sole charge weekends and public holidays, as required.'},
	{
	'title': 'Emergency Veterinarian',
	'url': 'emergencyveterinarian', 
	'pub_date': 'April 29, 2019', 
	'location': 'Melbroune VIC', 
	'type': 'Full time', 
	'sponsored': True, 
	'salary': 70000, 
	'description': 'A a growing, progressive small animal emergency practice dedicated to client service is looking for a full-time veterinarian.\n\nYou can expect all the trappings of a newly established Emergency & Specialist clinic: X-rays, CT Scan, endoscope, and a double theatre and much more. You will be exposed to exciting cases and have the opportunity to meet and work alongside industry specialists- the calibre of which you can only find here in Melbourne!\n\nThe management team are all experienced Vets who will work with you and encourage and enable you to flourish in your own personal/professional training and development.'},
	{
	'title': 'Dog Groomer', 
	'url': 'doggroomer',
	'pub_date': 'May 6, 2019', 
	'location': 'Sydney NSW', 
	'type': 'Part time', 
	'sponsored': False, 
	'salary': 35000, 
	'description': 'The role:\n\nOur grooming facilities are fully equipped including a height adjustable table and a free-standing dryer. We have a strong team of friendly and committed vets and nurses who are able to provide outstanding animal care and support to you.\nThe position will involve working 2 days per week with the possibility of further days as business increases.\n\nWhat you must have:\nExperience as an animal groomer\nGentle animal handling skills and a love of animals\nGood communication skills\nEnthusiasm and passion for working with pets and their owners.\nAttention to detail and take pride in your work.\nPlease apply online with your CV or via email to job@eppingvet.com.au or ramtin.safrang@vetpartners.com.au'},
	{
	'title': 'Equine Veterinarian', 
	'url': 'equineveterinarian',
	'pub_date': 'June 30, 2019', 
	'location': 'Canberra ACT 2600', 
	'type': 'Full time', 
	'sponsored': False, 
	'salary': 80000, 
	'description': 'Personal Suitability\n\nInitiative; Effective interpersonal skills; Flexibility; Accurate; Team player; Excellent oral communication; Excellent written communication; Dependability; Judgement; Values and ethics; Reliability\n\nWork Location Information Willing to relocate\n\nWork Conditions and Physical Capabilities\n\nFast-paced environment; Work under pressure; Repetitive tasks; Handling heavy loads; Physically demanding; Manual dexterity; Attention to detail; Hand-eye co-ordination; Ability to distinguish between colours; Combination of sitting, standing, walking; Standing for extended periods; Bending, crouching, kneeling\n\nWork Setting Veterinary clinic; Private practice\n\nSpecific Skills\n\nTreat sick or injured animals by prescribing medication, setting bones, dressing wounds or performing surgery; Diagnose diseases or abnormal conditions in individual animals, herds and flocks through physical examinations or laboratory tests; Vaccinate animals to prevent and treat diseases; Advise clients on feeding, housing, behaviour, breeding, hygiene and general care of animals; Provide a range of veterinary services including obstetrics, dentistry and euthanasia; Perform routine, emergency and post-mortem examinations'},
	{
	'title': 'Head Veterinarian',
	'url': 'headveterinarian', 
	'pub_date': 'March 1, 2019', 
	'location': 'Crandoune VIC', 
	'type': 'Part time', 
	'sponsored': True, 
	'salary': 90000, 
	'description': 'The Lost Dogs\' Home is one of the country\'s largest animal welfare organisations, caring for more than 20,000 cats and dogs each year. We pride ourselves on employing qualified individuals who demonstrate a strong commitment to animal welfare, shelter medicine, community education and the cause.\n\nWe are looking to appoint a Head Veterinarian (Full Time- 38hrs per week) at our Cranbourne Shelter. As a Head Veterinarian, you will build upon the success of the current team and drive the hospital forward, through;\nLeading a team of 4 veterinary staff members\nWorking closely with a senior vet nurse to continue the culture of collaboration, teamwork and excellence;\nWorking in conjunction with the North Melbourne Veterinary Team to improve strategies to manage patient flow, reduce length of stay and surgical waiting times;\nFostering and supporting the highest quality of teaching and mentoring of all hospital staff;\nThe recruitment, retention and professional development of high achieving veterinary staff with the full support if needed from our dedicated HR team.'},
	{
	'title': 'Veterinary Nurse',
	'url': 'veterinarynurse', 
	'pub_date': 'January 15, 2019', 
	'location': 'Lithgow NSW', 
	'type': 'Casual', 
	'sponsored': True, 
	'salary': 55000, 
	'description': 'WE’RE HIRING!\n\nLithgow Veterinary hospital has an exciting opportunity for a Veterinary Nurse.\n\n- Would you love to live close to the beautiful Blue Mountains, see the occasional snow fall and be surrounded by places of absolute natural beauty?\n- Would you love to work in a 2-3 vet clinic whose teams complete focus is exceptional patient care and delivering that something extra for all their clients?\n- Are you searching for a workplace that will mentor and support you and encourage your growth?\n\nWe are seeking someone who has been trained as a veterinary nurse but who still likes to occasionally rock out their reception skills to our great clients at the front desk.\n\nWe are a clinic that has been around for more than 30 years and we would love to find someone who wants to be part of an experience rather than just an everyday job.\n\nThe position is full time, part time or casual.'},
	{
	'title': 'Experienced Veterinary Nurse',
	'url': 'expveterinariannurse', 
	'pub_date': 'February 2, 2019', 
	'location': 'Smithton TAS', 
	'type': 'Full time', 
	'sponsored': False, 
	'salary': 65000, 
	'description': 'We are a busy mixed-practice vet clinic with dedicated reception staff, vet nurses and 5 veterinarians. The recently renovated clinic is located centrally in Smithton in a progressive and intensive farming district. It is equipped with digital radiography, ultrasound, orthopaedic gear, anaesthetic monitoring and in-house lab equipment for both small and large animals. Large animal facilities include on site equine stables and yards.\n\nThis is a permanent full time senior nurse position. Shifts are rostered Monday through Friday with no weekend or on-call requirement.\n\nGeneral duties will include:\n\nAssisting vets during small animal examinations and treatments\nAdmitting and discharging surgical patients and communicating with clients\nMonitoring anaesthetic procedures and patient recoveries\nConducting minor procedures when required\nNursing hospitalised animals and administering medications\nMaintaining a clean and tidy work environment including kennels, surgery and treatment areas\'nSupervision of junior veterinary nurses and animal attendants.\n\nThe ideal candidate will have:\n\nCert 4 or equivalent qualification with minimum 5 years’ experience\nExperience in a mixed practice environment. This is preferred but not essential\nExcellent communication skills and an ability to build rapport with both clients and colleagues\nA proactive, enthusiastic approach and be an outstanding team player who is willing to train and mentor junior staff\nCommitment to delivering the best outcomes for your patients'},
	{
	'title': 'Veterinarian - Saturdays', 
	'url': 'vetsaturdays',
	'pub_date': 'June 30, 2019', 
	'location': 'Brisbane QLD', 
	'type': 'Part time', 
	'sponsored': False, 
	'salary': 35000, 
	'description': 'The position:\n\nAn exciting opportunity exists for a Veterinarian to join our small animal clinic.\n\nThe hours for this position is Saturdays 8:00am-1:00 pm\n\nThe ideal candidate will possess:\nMinimum of 2 years\' experience as a small animal veterinarian\nA sound knowledge and understanding of high standards of care\nAbility to work independently with one nurse\nCapacity to build a rapport with clients\nExceptional organization and communication skills\nA positive and friendly attitude'},
	{
	'title': 'Experienced Dairy/Mixed Veterinarian',
	'url': 'expvetdairy', 
	'pub_date': 'May 17, 2019', 
	'location': 'Kyabram VIC', 
	'type': 'Full time', 
	'sponsored': False, 
	'salary': 55000, 
	'description': 'An experienced veterinarian is required to join a country practice, with a large animal focus in the Goulburn River Valley region of Victoria.\nIdeally, we are looking for an experienced dairy (or mixed with dairy focus) vet to work in a supportive veterinary team that delivers high calibre herd health programs to motivated producers.\nThe practice services an extensive dairy community. The dairy work consists of a mixture of clinic work and herd health. Bovine repro skills including competency in pregnancy testing, manual and ultrasound are needed for the role. Large animal yards and crushes are on site for surgery and other procedures.\n\nThe practice has a solid loyal small animal clientele and the practice has a growing number of equine clients. The clinic strives to consistently maintain the best practice ‘Standard Operating Procedures’ that are in place and to build and share skills in a positive and enjoyable work environment.'},
]